### ISSUE TITLE
Updated Poster for Capstone Showcase

### ISSUE THREAD

**Issue by keralab** [nolanslade/zp18#90]
Create new poster for the capstone showcase on April 3rd.
Need to update based on feedback from supervisors and poster requirements by the showcase organizers.
- 48” wide by 36” in height
- Simple, colourful, well-labeled and clear
- The title should be written in letters 1" to 2" high
- All material should be readable from a distance of 6 feet.

**Comment by keralab** [comment]
Poster from December: [final_poster.pptx](https://github.com/nolanslade/zp18/files/2998031/final_poster.pptx)
Updated V1 sent to supervisors: [updated_poster_v1.pptx](https://github.com/nolanslade/zp18/files/2998033/updated_poster_v1.pptx)

**Comment by keralab** [comment]
Not loving how this is looking but also its not our top priority.
Its due Monday so hopefully we can improve it a bit more by then.
[revised_poster.pptx](https://github.com/nolanslade/zp18/files/2999600/revised_poster.pptx)

**Comment by keralab** [comment]
We have sent the poster to Yasamin (TA) to be printed.

**Comment by keralab** [comment]
We have sent the poster to Yasamin (TA) to be printed.

**Comment by JacquesCarette** [comment]
Much better use of the space available. Lots more solid content. And I agree that visually, the previous one looked better!

Suggestions: put one of the rhs pictures at the top, and the other 2 at the bottom. Already that should give you better 'visuals'.  You could also consider putting the lhs picture between 'The Premise' and 'Original Simulation'. That will break the "wall of words" into smaller chunks.
You can also use a (very lightly) coloured background for the Motivation/Problem/Solution section, which will make it 'stand out' more.
[I know this might be too late - but maybe not, since it's quite possible Yasamin has not sent this off yet]
